spring.application.name=cb-search-service


server.port=7001
elastic.required.field.trending.search.json.path=/EsFieldsmapping/trendingSearchEsMapping.json
elastic.required.field.recent.search.json.path=/EsFieldsmapping/recentSearchesEsMapping.json

non.text.fields=search_count,last_searched,unique_id

elasticsearch.iGotESClient.host=localhost
elasticsearch.iGotESClient.port=9201
elasticsearch.iGotESClient.username=
elasticsearch.iGotESClient.password=

spring.cassandra.startupTimeoutInSeconds=100000
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=sunbird
spring.cassandra.username=sunbird
spring.cassandra.password=""
spring.cassandra.local-datacenter=DC1
sunbird_cassandra_consistency_level=ONE

cassandra.config.host=localhost


sso.url=https://portal.dev.karmayogibharat.net/auth/
sso.realm=sunbird
sso.connection.pool.size=20
sso.enabled=true

accesstoken.publickey.basepath=/home/arpithasureshappa/Downloads/publickey

#--------------------------kafka Server
spring.kafka.bootstrap.servers=localhost:9092
#-----------------kafka properties
kakfa.offset.reset.value=latest
kafka.max.poll.interval.ms=15000
kafka.max.poll.records=100
kafka.auto.commit.interval.ms=10000
kafka.topic.user.recent.searches=dev.user.recent.searches_test4
kafka.topic.user.recent.searches.group=user.recent.searches

#----------------Postgres-------------------------
spring.datasource.url=jdbc:postgresql://localhost:5433/sunbird
spring.datasource.username=sunbird
spring.datasource.password=sunbird
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update