spring.application.name=cb-search-service

server.port=7001


spring.cassandra.startupTimeoutInSeconds=100000
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=sunbird
spring.cassandra.username=sunbird
spring.cassandra.password=""
spring.cassandra.local-datacenter=DC1
sunbird_cassandra_consistency_level=ONE

cassandra.config.host=localhost


sso.url=https://portal.dev.karmayogibharat.net/auth/
sso.realm=sunbird
sso.connection.pool.size=20
sso.enabled=true

accesstoken.publickey.basepath=/publickey


spring.redis.cacheTtl=604800

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=



